main_menu = [
    {
        "text": "Flush DNS Cache",
        "description": "Flushes the DNS cache to resolve DNS-related issues.",
        "command": "ipconfig /flushdns",
        "success_message": "DNS cache flushed successfully.",
        "long_description": "Use this command to flush the DNS cache when you are experiencing DNS-related issues such as not being able to resolve domain names.",
    },
    {
        "text": "Clear ARP Cache",
        "description": "Clears the ARP cache to resolve ARP-related issues.",
        "command": "arp -d",
        "success_message": "ARP cache cleared successfully.",
        "long_description": "Use this command to clear the ARP cache when you are experiencing ARP-related issues such as incorrect IP address to MAC address mappings.",
    },
    {
        "text": "Test Connectivity",
        "description": "Tests network connectivity by pinging common DNS servers.",
        "submenu": "test_connectivity",
        "long_description": "Use this submenu to test network connectivity by pinging common DNS servers like Google DNS, Cloudflare DNS, and OpenDNS.",
    },
    {
        "text": "Display DNS Cache",
        "description": "Displays the current DNS cache entries.",
        "command": "ipconfig /displaydns",
        "success_message": "DNS cache displayed.",
        "long_description": "Use this command to display the current DNS cache entries to troubleshoot DNS resolution issues.",
    },
    {
        "text": "Reset Network Settings",
        "description": "Resets network settings to default.",
        "command": "netsh int ip reset",
        "success_message": "Network settings reset successfully.",
        "long_description": "Use this command to reset network settings to their default values when you are experiencing network configuration issues.",
    },
    {
        "text": "Release and Renew IP Address",
        "description": "Releases and renews the IP address.",
        "command": "ipconfig /release && ipconfig /renew",
        "success_message": "IP address released and renewed.",
        "long_description": "Use this command to release and renew the IP address when you are experiencing IP address conflicts or connectivity issues.",
    },
    {
        "text": "Check Network Adapter Status",
        "description": "Displays the status of network adapters.",
        "command": "netsh interface show interface",
        "success_message": "Network adapter status displayed.",
        "long_description": "Use this command to display the status of network adapters to troubleshoot connectivity issues.",
    },
    {
        "text": "Reset Winsock",
        "description": "Resets Winsock settings. Requires a restart.",
        "command": "netsh winsock reset",
        "success_message": "Winsock reset successfully. Please restart your computer for changes to take effect.",
        "long_description": "Use this command to reset Winsock settings when you are experiencing network socket-related issues. A restart is required for changes to take effect.",
    },
    {
        "text": "Reset TCP/IP Stack (IPv4)",
        "description": "Resets the IPv4 TCP/IP stack. Requires a restart.",
        "command": "netsh int ip reset",
        "success_message": "IPv4 TCP/IP stack reset successfully. Please restart your computer for changes to take effect.",
        "long_description": "Use this command to reset the IPv4 TCP/IP stack when you are experiencing IPv4-related connectivity issues. A restart is required for changes to take effect.",
    },
    {
        "text": "Reset TCP/IP Stack (IPv6)",
        "description": "Resets the IPv6 TCP/IP stack. Requires a restart.",
        "command": "netsh int ipv6 reset",
        "success_message": "IPv6 TCP/IP stack reset successfully. Please restart your computer for changes to take effect.",
        "long_description": "Use this command to reset the IPv6 TCP/IP stack when you are experiencing IPv6-related connectivity issues. A restart is required for changes to take effect.",
    },
    {
        "text": "Restart DHCP and DNS Client Services",
        "description": "Restarts DHCP and DNS Client services.",
        "command": "net stop dhcp && net start dhcp && net stop dnscache && net start dnscache",
        "success_message": "DHCP and DNS Client services restarted.",
        "long_description": "Use this command to restart DHCP and DNS Client services when you are experiencing issues with obtaining an IP address or DNS resolution.",
    },
    {
        "text": "Restart Network Adapters",
        "description": "Restarts network adapters.",
        "command": 'for /f "tokens=*" %%A in (\'netsh interface show interface ^| findstr /C:"Enabled"\') do (netsh interface set interface name="%%A" admin=disable && timeout /t 2 >nul && netsh interface set interface name="%%A" admin=enable)',
        "success_message": "Network adapters restarted.",
        "long_description": "Use this command to restart network adapters when you are experiencing connectivity issues.",
    },
    {
        "text": "Display Network Configuration",
        "description": "Displays the current network configuration.",
        "command": "ipconfig /all",
        "success_message": "Network configuration displayed.",
        "long_description": "Use this command to display the current network configuration to troubleshoot network settings and connectivity issues.",
    },
    {
        "text": "Check for Network Driver Updates",
        "description": "Checks for updates to network drivers.",
        "command": "wmic path win32_pnpentity where \"DeviceID like '%%PCI%%'\" get DeviceID, Name, Manufacturer, DriverVersion",
        "success_message": "Network driver updates check completed.",
        "long_description": "Use this command to check for updates to network drivers when you are experiencing driver-related issues.",
    },
    {"text": "Help", "submenu": "help_menu"},
    {
        "text": "Flush DNS, Clear ARP, and Test Connectivity",
        "description": "Flushes DNS, clears ARP, and tests connectivity.",
        "commands": [
            {
                "command": "ipconfig /flushdns",
                "success_message": "DNS cache flushed successfully.",
                "long_description": "Use this command to flush the DNS cache when you are experiencing DNS-related issues such as not being able to resolve domain names.",
            },
            {
                "command": "arp -d",
                "success_message": "ARP cache cleared successfully.",
                "long_description": "Use this command to clear the ARP cache when you are experiencing ARP-related issues such as incorrect IP address to MAC address mappings.",
            },
            {
                "command": "ping 8.8.8.8 -n 4",
                "success_message": "Ping to Google DNS complete.",
                "long_description": "Use this command to test network connectivity by pinging Google DNS.",
            },
        ],
    },
]

help_menu = [
    {
        "text": "Flush DNS",
        "description": "Flush DNS Cache",
        "command": "ipconfig /flushdns /?",
        "long_description": "Use this command to get help on flushing the DNS cache.",
    },
    {
        "text": "Clear ARP",
        "description": "Clear ARP Cache",
        "command": "arp -d /?",
        "long_description": "Use this command to get help on clearing the ARP cache.",
    },
    {
        "text": "Ping",
        "description": "Test Connectivity",
        "command": "ping /?",
        "long_description": "Use this command to get help on testing connectivity using ping.",
    },
    {
        "text": "Display DNS",
        "description": "Display DNS Cache",
        "command": "ipconfig /displaydns /?",
        "long_description": "Use this command to get help on displaying the DNS cache.",
    },
    {
        "text": "Reset Network",
        "description": "Reset Network Settings",
        "command": "netsh int ip reset /?",
        "long_description": "Use this command to get help on resetting network settings.",
    },
    {
        "text": "Release/Renew IP",
        "description": "Release and Renew IP Address",
        "command": "ipconfig /release && ipconfig /renew /?",
        "long_description": "Use this command to get help on releasing and renewing the IP address.",
    },
    {
        "text": "Check Adapter",
        "description": "Check Network Adapter Status",
        "command": "netsh interface show interface /?",
        "long_description": "Use this command to get help on checking the network adapter status.",
    },
    {
        "text": "Reset Winsock",
        "description": "Reset Winsock",
        "command": "netsh winsock reset /?",
        "long_description": "Use this command to get help on resetting Winsock.",
    },
    {
        "text": "Reset IPv4",
        "description": "Reset TCP/IP Stack (IPv4)",
        "command": "netsh int ip reset /?",
        "long_description": "Use this command to get help on resetting the IPv4 TCP/IP stack.",
    },
    {
        "text": "Reset IPv6",
        "description": "Reset TCP/IP Stack (IPv6)",
        "command": "netsh int ipv6 reset /?",
        "long_description": "Use this command to get help on resetting the IPv6 TCP/IP stack.",
    },
    {
        "text": "Restart Services",
        "description": "Restart DHCP and DNS Client Services",
        "command": "net stop dhcp && net start dhcp && net stop dnscache && net start dnscache /?",
        "long_description": "Use this command to get help on restarting DHCP and DNS Client services.",
    },
    {
        "text": "Restart Adapters",
        "description": "Restart Network Adapters",
        "command": 'netsh interface set interface name="[Adapter Name]" admin=disable && netsh interface set interface name="[Adapter Name]" admin=enable /?',
        "long_description": "Use this command to get help on restarting network adapters.",
    },
    {
        "text": "Check Internet",
        "description": "Check Internet Connectivity",
        "command": "ping www.google.com /?",
        "long_description": "Use this command to get help on checking internet connectivity.",
    },
    {
        "text": "Display Config",
        "description": "Display Network Configuration",
        "command": "ipconfig /all /?",
        "long_description": "Use this command to get help on displaying the network configuration.",
    },
    {
        "text": "Check Drivers",
        "description": "Check for Network Driver Updates",
        "command": "wmic path win32_pnpentity where \"DeviceID like '%%PCI%%'\" get DeviceID, Name, Manufacturer, DriverVersion /?",
        "long_description": "Use this command to get help on checking for network driver updates.",
    },
    {"text": "Back to Main Menu", "submenu": "main_menu"},
]

test_connectivity = [
    {
        "text": "Ping Google DNS (8.8.8.8)",
        "description": "Pings Google DNS to test connectivity.",
        "command": "ping 8.8.8.8 -n 4",
        "success_message": "Ping to Google DNS complete.",
        "long_description": "Use this command to test network connectivity by pinging Google DNS.",
    },
    {
        "text": "Ping Cloudflare DNS (1.1.1.1)",
        "description": "Pings Cloudflare DNS to test connectivity.",
        "command": "ping 1.1.1.1 -n 4",
        "success_message": "Ping to Cloudflare DNS complete.",
        "long_description": "Use this command to test network connectivity by pinging Cloudflare DNS.",
    },
    {
        "text": "Ping OpenDNS (208.67.222.222)",
        "description": "Pings OpenDNS to test connectivity.",
        "command": "ping 208.67.222.222 -n 4",
        "success_message": "Ping to OpenDNS complete.",
        "long_description": "Use this command to test network connectivity by pinging OpenDNS.",
    },
    {
        "text": "Enter Custom IP",
        "description": "Enter IP to ping:",
        "custom_input": True,
        "long_description": "Use this option to enter a custom IP address to ping.",
    },
    {"text": "Back to Main Menu", "submenu": "main_menu"},
]
